module.exports = {
  ERROR_STORAGE_PARAM_NOT_VALID : 100,
  ERROR_INIT_OPTIONS_NOT_DEFINED : 101,
  ERROR_STORAGE_NOT_EXISTS : 200,
  ERROR_PERSISTENCE_ERROR: 210,
  DEFAULT_COLLECTION_ROOT : 'grid_fs',
  DEFAULT_CONTENT_TYPE: 'plain/text',
  DEFAULT_CHUNK_SIZE: 2048
};
